del 10d_src.zip
%kzd%:\b\bin\wzzip 10d_src *.c *.cpp *.h *.hg *.hst *.hky *.vml *.pdg *.pmd *.pwd *.lod *.pog *.pdg -P -r -x@zzsrc.exc %1
%kzd%:\b\bin\wzzip 10d_src *.ppe *.psa *.pui *.pvr *.mak *.xdm *.xgo *.xmd *.xod *.xpe *.xwd -P -r -x@zzsrc.exc %1

%kzd%:\b\bin\wzzip 10d_src -d w\oe\dg\*.*  -d w\oe\back\*.*  -d w\oe\dks\*.*
%kzd%:\b\bin\wzzip 10d_src -d w\oe\hold\*.*  -d w\oe\10b\*.*  -d w\oe\10d\*.*
%kzd%:\b\bin\wzzip 10d_src -d a\oe\dg\*.*  -d a\oe\back\*.*  -d a\oe\dks\*.*
%kzd%:\b\bin\wzzip 10d_src -d a\oe\hold\*.*  -d a\oe\10b\*.*  -d a\oe\10d\*.*
