//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ZDr.rc
//
#define IDR_MANIFEST                    1
#define VIEW_EDIT                       1
#define IDB_TEXT                        1
#define VIEW_LISTCTRL                   2
#define IDB_PALETTE                     2
#define VIEW_SPLITTER                   3
#define IDB_GRAPH                       3
#define IDB_EDIT                        7
#define IDB_PUSHBTN                     8
#define IDB_BITMAPBTN                   9
#define IDB_ICON                        10
#define IDB_RADIOBTN                    11
#define IDB_CHECKBOX                    13
#define IDB_COMBOBOX                    14
#define IDB_LISTBOX                     15
#define IDB_GROUPBOX                    16
#define IDB_TAB                         17
#define IDB_MLE                         18
#define IDB_SS                          19
#define IDB_DIL                         20
#define IDB_OUTLINER                    21
#define IDB_HIERDIAGRAM                 23
//#define RT_MANIFEST                     MAKEINTRESOURCE(24)
#define IDB_BLOCK                       25
#define IDB_BITMAP                      28
#define IDB_GROUPSET                    30
#define IDB_GROUP                       31
#define IDB_SHAPE                       32
#define IDB_CALENDAR                    33
#define IDB_TIMER                       34
#define IDB_TOOLBAR                     35
#define IDB_EDITGRP                     37
#define IDB_CONTROLBAR                  39
#define IDB_DAYTIMER                    41
#define IDB_SSSUB                       42
#define IDB_TREE_CLOSED                 129
#define IDB_TREE_OPENED                 130
#define IDB_GRID                        139
#define IDB_ACTIVEX                     140
#define IDD_DIALOG2                     162
#define IDB_TREECLOSE                   200
#define IDB_TREEOPEN                    201
#define IDB_TREESELECT                  202
#define IDB_PREV_END                    220
#define IDB_PREV_HOME                   221
#define IDB_PREV_NEXT                   222
#define IDB_PREV_ONE                    223
#define IDB_PREV_PREVIOUS               224
#define IDB_PREV_PRINT                  225
#define IDB_PREV_TWO                    226
#define IDB_PREV_ZOOMIN                 237
#define IDB_PREV_ZOOMOUT                238
#define IDB_APPOINTMENT_ALARM           301
#define IDB_APPOINTMENT_BKGND           302
#define IDB_BCGCALENDAR                 304
#define IDB_BCGDATETIME                 305
#define IDB_CALENDAR_BUTTONS            306
#define IDB_DATE_IMAGES                 307
#define IDB_GLYPHS                      308
#define IDB_CB_CHECKMARK                309
#define IDB_CB_XCHECK                   310
#define IDB_CB_LED                      311
#define IDC_BCOPY1                      401
#define IDC_BCOPYM                      402
#define IDC_BDROPNOT                    403
#define IDC_BMOVE                       404
#define IDC_BMOVE1                      405
#define IDC_BMOVEM                      406
#define IDC_BPROMOTE                    407
#define IDC_CHECK1                      408
#define IDC_CHECK2                      409
#define IDC_CHECK3                      410
#define IDC_CHECK4                      411
#define IDC_CHECK5                      412
#define IDC_CHECK6                      413
#define IDC_DRAGGING                    414
#define IDC_DROPNOT                     415
#define IDC_DROPOKC1                    416
#define IDC_DROPOKCM                    417
#define IDC_DROPOKM                     418
#define IDC_DROPOKM1                    419
#define IDC_DROPOKMM                    420
#define IDC_HAND1                       421
#define IDC_HAND2                       422
#define IDC_HANDX                       423
#define IDC_HSPLIT                      424
#define IDC_INPUT                       425
#define IDC_LIST_SUBTASKS               426
#define IDC_NODRAGGING                  427
#define IDC_PROMPT                      428
#define IDC_TITLE                       429
#define IDC_VSPLIT                      430
#define IDC_XSPLIT                      431
#define IDD_DIALOGUNITS                 500
#define IDD_EDITVIEW                    501
#define IDD_FORMVIEW1                   502
#define IDD_FORMVIEW2                   503
#define IDD_FORMVIEW3                   504
#define IDD_LEFT                        505
#define IDD_LISTCTRLVIEW                506
#define IDD_MODALDLG                    507
#define IDD_PREVIEW                     508
#define IDD_SUBTASKS                    509
#define IDD_TREEVIEW                    510
#define IDD_VIEW1                       511
#define IDD_VIEW2                       512
#define IDD_VIEW3                       513
#define IDI_FOLDERCLOSE                 600
#define IDI_FOLDEROPEN                  601
#define IDI_FOLDERSELECT                602
#define IDI_PINNED                      603
#define IDI_UNPINNED                    604
#define IDP_FAILED_TO_CREATE            610
#define IDP_OLE_INIT_FAILED             611
#define IDR_CNTR_INPLACE                700
#define IDR_COLOR_MAINBAR               701
#define IDR_MAINFRAME                   702
#define IDR_MAINFRAMEX                  703
#define IDR_PAINTER_CONTROL             704
#define IDR_POPUPMENUS                  705
#define IDR_TABCTRL                     706
#define IDR_TEXTTYPE                    707
#define IDS_CALENDAR_BKGND              801
#define IDS_CALENDAR_WORKDAY            802
#define IDS_CANNOT_CREATE_NEW_SWITCHSPLIT 803
#define IDS_NEW_SWITCH_SPLIT_FILE       804
#define IDS_HELLO                       805
#define IDS_NEXT_MONTH                  806
#define IDS_NEXT_YEAR                   807
#define IDS_PREV_MONTH                  808
#define IDS_PREV_YEAR                   809
#define IDS_TODAY                       810
#define ID_ADD_FORM_VIEW                900
#define ID_APP_SPLIT                    901
#define ID_GFX_LARGEICON                902
#define ID_GFX_REMOVEITEM               903
#define ID_GFX_RENAMEITEM               904
#define ID_GFX_SMALLICON                905
#define ID_MICROSOFT_HOME               906
#define ID_REMOVE_FORM_VIEW             907
#define ID_VIEW_EDITVIEW                908
#define ID_VIEW_FORMVIEW1               909
#define ID_VIEW_FORMVIEW2               910
#define ID_VIEW_LISTVIEW                911
#define ID_VIEW_SPLITTER                912
#define IDC_VIEW1                       1002
#define IDC_VIEW2                       1003
#define IDC_COMBO1                      1004
#define IDC_VIEW3                       1005
#define IDC_LIST1                       1006
#define IDC_SLIDER1                     1007
#define IDC_SLIDER2                     1008
#define IDC_SLIDER3                     1009
#define IDC_RADIO1                      1010
#define IDC_RADIO2                      1011
#define IDC_RADIO3                      1012
#define IDC_BUTTON1                     1013
#define IDC_REPLACE                     0x0400
#define IDC_REPLACE_ALL                 0x0401
#define IDC_TREE                        1030
#define IDC_LIST                        1031
#define IDC_EDIT                        1032
#define IDC_COMBOFIND_WHAT              0x0480
#define IDC_REPLACE_WITH                0x0481
#define IDD_DIALOG1                     2000
#define IDW_MAIN_BAR                    2001
#define IDD_ABOUTBOX                    2002
#define IDW_RESOURCE_BAR                2003
#define IDD_INPUTFORM                   2004
#define IDW_DEBUG_BAR                   2005
#define IDW_EDIT_BAR                    2006
#define IDD_INPUTDIALOG                 2007
#define IDW_BROWSE_BAR                  2009
#define IDD_PROPERTY                    2010
#define IDW_PAINTER_BAR                 2011
#define IDW_PAINTER_PALETTE             2012
#define IDD_ABOUTBOXX                   2013
#define IDD_ZREPLACEDLG                 2014
#define IDD_ZFINDDLG                    2015
#define IDD_DIALOGBAR1                  2016
#define IDR_LISTOUTPUT                  2017
#define IDW_WORK_BAR                    2019
#define IDS_APRPOPNAME                  2050
#define IDS_APROPNAME_USERMODE          2051
#define IDS_APROPNAME_UIDEAD            2052
#define IDS_APROPNAME_SHOWHATCHING      2053
#define IDS_APROPNAME_SHOWGRABHANDLES   2054
#define IDS_APROPNAME_TEXTALIGN         2055
#define IDS_APROPNAME_BACKCOLOR         2056
#define IDS_APROPNAME_FORECOLOR         2057
#define IDS_APROPNAME_FONT              2058
#define IDS_APROPNAME_DISPLAYNAME       2059
#define IDS_APROPNAME_SCALEUNITS        2060
#define IDS_APROPNAME_MESSAGEREFLECT    2061
#define IDS_APROPNAME_LOCALEID          2062
#define IDS_APROPNAME_SUPPORTSMNEMONICS 2063
#define ID_DUMP_CLASSES                 32768
#define ID_DUMP_OBJECTS                 32769
#define ID_DUMP_DOCTEMPLATES            32770
#define ID_DUMP_DLLS                    32771
#define ID_CANCEL_EDIT_CNTR             32772
#define ID_BUTTON32773                  32773
#define ID_BUTTON32774                  32774
#define ID_BUTTON32775                  32775
#define ID_BUTTON32776                  32776
#define ID_BUTTON32777                  32777
#define ID_KEY_LEFT                     32778
#define ID_KEY_RIGHT                    32779
#define ID_KEY_CTAB                     32780
#define ID_KEY_SCTAB                    32781
#define ID_KEY_END                      32782
#define ID_KEY_HOME                     32783
#define ID_KEY_TAB                      32784
#define ID_KEY_STAB                     32785
#define ID_KEY_UP                       32786
#define ID_KEY_DOWN                     32787
#define ID_BUTTON32788                  32788
#define ID_BUTTON32800                  32800
#define ID_BUTTON32801                  32801
#define ID_BUTTON32802                  32802
#define ID_BUTTON32803                  32803
#define ID_BUTTON32804                  32804
#define ID_BUTTON32805                  32805
#define ID_BUTTON32806                  32806
#define ID_BUTTON32807                  32807
#define ID_BUTTON32808                  32808
#define ID_BUTTON32809                  32809
#define ID_BUTTON32810                  32810
#define ID_BUTTON32811                  32811
#define ID_BUTTON32812                  32812
#define ID_BUTTON32813                  32813
#define ID_BUTTON32814                  32814
#define ID_BUTTON32815                  32815
#define ID_BUTTON32816                  32816
#define ID_BUTTON32817                  32817
#define ID_BUTTON32818                  32818
#define ID_BUTTON32819                  32819
#define IDM_BLACK                       0x9000
#define IDM_RED                         0x9001
#define IDM_GREEN                       0x9002
#define IDM_BLUE                        0x9003
#define IDM_WHITE                       0x9004
#define IDM_CUSTOM                      0x9005
#define ID_ACTION_BAR_UPDATE            0xE820
#define ID_ALIGN_LEFT                   0xE821
#define ID_ALIGN_TOP                    0xE822
#define ID_ALIGN_RIGHT                  0xE823
#define ID_ALIGN_BOTTOM                 0xE824
#define ID_SIZE_WIDTH                   0xE825
#define ID_SIZE_HEIGHT                  0xE826
#define ID_SIZE_WIDTH_HEIGHT            0xE827
#define ID_EQUAL_SPACE_HORIZONTAL       0xE828
#define ID_EQUAL_SPACE_VERTICAL         0xE829
#define ID_ABUT_HORIZONTAL              0xE82A
#define ID_ABUT_VERTICAL                0xE82B
#define ID_DELETE_SELECTED              0xE82C
#define ID_EQUAL_SIZE_POS_CLASS         0xE82D
#define ID_GROUP_SELECTED               0xE82E
#define ID_UNGROUP_SELECTED             0xE82F
#define ID_TOOLBAR_WNDLIST              0xE830
#define ID_TOOLBAR_ACTLIST              0xE831
#define ID_TOOLBAR_OPERLIST             0xE832
#define ID_ARROW                        0xE833

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         160
#define _APS_NEXT_SYMED_VALUE           42
#endif
#endif
