/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zeidon_zView */

#ifndef _Included_zeidon_zView
#define _Included_zeidon_zView
#ifdef __cplusplus
extern "C" {
#endif
#undef zeidon_zView_zPOS_FIRST
#define zeidon_zView_zPOS_FIRST 1L
#undef zeidon_zView_zPOS_LAST
#define zeidon_zView_zPOS_LAST 2L
#undef zeidon_zView_zPOS_NEXT
#define zeidon_zView_zPOS_NEXT 3L
#undef zeidon_zView_zPOS_AFTER
#define zeidon_zView_zPOS_AFTER 3L
#undef zeidon_zView_zPOS_PREV
#define zeidon_zView_zPOS_PREV 4L
#undef zeidon_zView_zPOS_BEFORE
#define zeidon_zView_zPOS_BEFORE 4L
#undef zeidon_zView_zSINGLE
#define zeidon_zView_zSINGLE 0L
#undef zeidon_zView_zMULTIPLE
#define zeidon_zView_zMULTIPLE 256L
#undef zeidon_zView_zNOI_OKAY
#define zeidon_zView_zNOI_OKAY 512L
#undef zeidon_zView_zNOENQUEUE
#define zeidon_zView_zNOENQUEUE 1024L
#undef zeidon_zView_zREADONLY
#define zeidon_zView_zREADONLY 2048L
#undef zeidon_zView_zSINGLE_FOR_UPDATE
#define zeidon_zView_zSINGLE_FOR_UPDATE 4194304L
#undef zeidon_zView_zIGNORE_ENTITY_ERRORS
#define zeidon_zView_zIGNORE_ENTITY_ERRORS 4096L
#undef zeidon_zView_zIGNORE_ATTRIB_ERRORS
#define zeidon_zView_zIGNORE_ATTRIB_ERRORS 8192L
#undef zeidon_zView_zACTIVATE_CONTINUE
#define zeidon_zView_zACTIVATE_CONTINUE 8388608L
#undef zeidon_zView_zACTIVATE_LOCAL
#define zeidon_zView_zACTIVATE_LOCAL 1073741824L
#undef zeidon_zView_zACTIVATE_SYSTEM
#define zeidon_zView_zACTIVATE_SYSTEM 536870912L
#undef zeidon_zView_zACTIVATE_ROOTONLY
#define zeidon_zView_zACTIVATE_ROOTONLY 268435456L
#undef zeidon_zView_zACTIVATE_NOCONSTRAINTS
#define zeidon_zView_zACTIVATE_NOCONSTRAINTS 16777216L
#undef zeidon_zView_zIGNORE_ERRORS
#define zeidon_zView_zIGNORE_ERRORS 12288L
#undef zeidon_zView_zACTIVATE_ROOTONLY_MULTIPLE
#define zeidon_zView_zACTIVATE_ROOTONLY_MULTIPLE 268435712L
#undef zeidon_zView_zACTIVATE_ROOTONLY_CONTINUE
#define zeidon_zView_zACTIVATE_ROOTONLY_CONTINUE 276824320L
#undef zeidon_zView_zACTIVATE_MULTIPLE_CONTINUE
#define zeidon_zView_zACTIVATE_MULTIPLE_CONTINUE 8388864L
#undef zeidon_zView_zCALL_ERROR
#define zeidon_zView_zCALL_ERROR -16L
#undef zeidon_zView_zCURSOR_NULL
#define zeidon_zView_zCURSOR_NULL -3L
#undef zeidon_zView_zCURSOR_UNDEFINED
#define zeidon_zView_zCURSOR_UNDEFINED -2L
#undef zeidon_zView_zCURSOR_UNCHANGED
#define zeidon_zView_zCURSOR_UNCHANGED -1L
#undef zeidon_zView_zCURSOR_SET
#define zeidon_zView_zCURSOR_SET 0L
#undef zeidon_zView_zCURSOR_SET_NEWPARENT
#define zeidon_zView_zCURSOR_SET_NEWPARENT 1L
#undef zeidon_zView_zCURSOR_SET_RECURSIVECHILD
#define zeidon_zView_zCURSOR_SET_RECURSIVECHILD 2L
#undef zeidon_zView_zREPOS_NONE
#define zeidon_zView_zREPOS_NONE 0L
#undef zeidon_zView_zREPOS_FIRST
#define zeidon_zView_zREPOS_FIRST 1L
#undef zeidon_zView_zREPOS_LAST
#define zeidon_zView_zREPOS_LAST 2L
#undef zeidon_zView_zREPOS_NEXT
#define zeidon_zView_zREPOS_NEXT 3L
#undef zeidon_zView_zREPOS_AFTER
#define zeidon_zView_zREPOS_AFTER 3L
#undef zeidon_zView_zREPOS_PREV
#define zeidon_zView_zREPOS_PREV 4L
#undef zeidon_zView_zREPOS_BEFORE
#define zeidon_zView_zREPOS_BEFORE 4L
#undef zeidon_zView_zXML_ZEIDONINFO
#define zeidon_zView_zXML_ZEIDONINFO 1L
#undef zeidon_zView_zXML_INCREFLAGS
#define zeidon_zView_zXML_INCREFLAGS 2L
#undef zeidon_zView_zXML_UPDATEDONLY
#define zeidon_zView_zXML_UPDATEDONLY 4L
#undef zeidon_zView_zXML_ENTITYKEYS
#define zeidon_zView_zXML_ENTITYKEYS 8L
#undef zeidon_zView_zXML_KEYATTRIBSASIDENT
#define zeidon_zView_zXML_KEYATTRIBSASIDENT 16L
#undef zeidon_zView_zXML_ROOTONLY
#define zeidon_zView_zXML_ROOTONLY 32L
#undef zeidon_zView_zENTITY_SELECTED
#define zeidon_zView_zENTITY_SELECTED 1L
#undef zeidon_zView_zENTITY_UNSELECTED
#define zeidon_zView_zENTITY_UNSELECTED 0L
/*
 * Class:     zeidon_zView
 * Method:    niRegisterZeidonApplication
 * Signature: (Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niRegisterZeidonApplication
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niUnregisterZeidonApplication
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niUnregisterZeidonApplication
  (JNIEnv *, jobject, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetDefaultViewForActiveTask
 * Signature: (Ljava/lang/String;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetDefaultViewForActiveTask
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     zeidon_zView
 * Method:    niDisplayObjectInstance
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niDisplayObjectInstance
  (JNIEnv *, jobject, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niDisplayEntityInstance
 * Signature: (Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niDisplayEntityInstance
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niGarbageCollectViews
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niGarbageCollectViews
  (JNIEnv *, jobject, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niGetIntegerFromView
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_zeidon_zView_niGetIntegerFromView
  (JNIEnv *, jobject, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niActivateEmpty
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lzeidon/zView;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niActivateEmpty
  (JNIEnv *, jobject, jstring, jstring, jobject, jint);

/*
 * Class:     zeidon_zView
 * Method:    niSfActivateSysEmptyOI
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lzeidon/zView;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSfActivateSysEmptyOI
  (JNIEnv *, jobject, jstring, jstring, jobject, jint);

/*
 * Class:     zeidon_zView
 * Method:    niActivate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lzeidon/zView;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niActivate__Ljava_lang_String_2Ljava_lang_String_2Lzeidon_zView_2I
  (JNIEnv *, jobject, jstring, jstring, jobject, jint);

/*
 * Class:     zeidon_zView
 * Method:    niActivate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lzeidon/zView;Lzeidon/zView;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niActivate__Ljava_lang_String_2Ljava_lang_String_2Lzeidon_zView_2Lzeidon_zView_2I
  (JNIEnv *, jobject, jstring, jstring, jobject, jobject, jint);

/*
 * Class:     zeidon_zView
 * Method:    niActivateFromFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lzeidon/zView;Ljava/lang/String;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niActivateFromFile
  (JNIEnv *, jobject, jstring, jstring, jobject, jstring, jint);

/*
 * Class:     zeidon_zView
 * Method:    Commit
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_Commit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     zeidon_zView
 * Method:    CommitOI_ToXML_File
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_CommitOI_1ToXML_1File
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     zeidon_zView
 * Method:    CommitSubobjectToXML_File
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_CommitSubobjectToXML_1File
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     zeidon_zView
 * Method:    GetTableListForAttribute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_zeidon_zView_GetTableListForAttribute
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niGetView
 * Signature: (Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niGetView__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niGetView
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lzeidon/zView;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niGetView__Ljava_lang_String_2Ljava_lang_String_2Lzeidon_zView_2
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     zeidon_zView
 * Method:    niGetView
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lzeidon/zView;S)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niGetView__Ljava_lang_String_2Ljava_lang_String_2Lzeidon_zView_2S
  (JNIEnv *, jobject, jstring, jstring, jobject, jshort);

/*
 * Class:     zeidon_zView
 * Method:    niSetName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetName__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetName
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lzeidon/zView;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetName__Ljava_lang_String_2Ljava_lang_String_2Lzeidon_zView_2
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     zeidon_zView
 * Method:    niSetName
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lzeidon/zView;S)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetName__Ljava_lang_String_2Ljava_lang_String_2Lzeidon_zView_2S
  (JNIEnv *, jobject, jstring, jstring, jobject, jshort);

/*
 * Class:     zeidon_zView
 * Method:    niCreateViewFromView
 * Signature: (Ljava/lang/String;Lzeidon/zView;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niCreateViewFromView
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     zeidon_zView
 * Method:    niDropName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niDropName
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niDropView
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niDropView
  (JNIEnv *, jobject, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niDropObjectInstance
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niDropObjectInstance
  (JNIEnv *, jobject, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niTraceLine
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_zeidon_zView_niTraceLine__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niTraceLine
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_zeidon_zView_niTraceLine__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     zeidon_zView
 * Method:    niTraceLine
 * Signature: (Ljava/lang/String;Lzeidon/zView;)V
 */
JNIEXPORT void JNICALL Java_zeidon_zView_niTraceLine__Ljava_lang_String_2Lzeidon_zView_2
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     zeidon_zView
 * Method:    niSetOIFromBlob
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lzeidon/zView;Lzeidon/zView;Ljava/lang/String;Ljava/lang/String;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetOIFromBlob
  (JNIEnv *, jobject, jstring, jstring, jobject, jobject, jstring, jstring, jint);

/*
 * Class:     zeidon_zView
 * Method:    niSetBlobFromOI
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lzeidon/zView;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetBlobFromOI
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject, jint);

/*
 * Class:     zeidon_zView
 * Method:    niOrderEntityForView
 * Signature: (Ljava/lang/String;Lzeidon/zView;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niOrderEntityForView
  (JNIEnv *, jobject, jstring, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niCreateEntity
 * Signature: (Ljava/lang/String;Ljava/lang/String;S)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niCreateEntity
  (JNIEnv *, jobject, jstring, jstring, jshort);

/*
 * Class:     zeidon_zView
 * Method:    niSetSelectStateOfEntity
 * Signature: (Ljava/lang/String;Ljava/lang/String;S)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetSelectStateOfEntity
  (JNIEnv *, jobject, jstring, jstring, jshort);

/*
 * Class:     zeidon_zView
 * Method:    niSetAllSelectStatesForEntity
 * Signature: (Ljava/lang/String;Ljava/lang/String;SLjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetAllSelectStatesForEntity
  (JNIEnv *, jobject, jstring, jstring, jshort, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niGetSelectStateOfEntity
 * Signature: (Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niGetSelectStateOfEntity
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niCheckExistenceOfEntity
 * Signature: (Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niCheckExistenceOfEntity
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niDeleteEntity
 * Signature: (Ljava/lang/String;Ljava/lang/String;S)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niDeleteEntity
  (JNIEnv *, jobject, jstring, jstring, jshort);

/*
 * Class:     zeidon_zView
 * Method:    niIncludeSubobjectFromSubobject
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lzeidon/zView;Ljava/lang/String;S)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niIncludeSubobjectFromSubobject
  (JNIEnv *, jobject, jstring, jstring, jobject, jstring, jshort);

/*
 * Class:     zeidon_zView
 * Method:    niExcludeEntity
 * Signature: (Ljava/lang/String;Ljava/lang/String;S)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niExcludeEntity
  (JNIEnv *, jobject, jstring, jstring, jshort);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorEntityKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorEntityKey
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorScopeOI
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorScopeOI
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursor
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursor
  (JNIEnv *, jobject, jstring, jstring, jint, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorFirst
 * Signature: (Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorFirst__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorFirst
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorFirst__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorFirst
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorFirst__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorFirst
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;DLjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorFirst__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2DLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jdouble, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorFirst
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorFirst__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorLast
 * Signature: (Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorLast__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorLast
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorLast__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorNext
 * Signature: (Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorNext__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorNext
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorNext__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorNext
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorNext__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorNext
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;DLjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorNext__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2DLjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jdouble, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorNext
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorNext__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorPrev
 * Signature: (Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorPrev__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetCursorPrev
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetCursorPrev__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niGetEntityKey
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_zeidon_zView_niGetEntityKey
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niGetInteger
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_zeidon_zView_niGetInteger
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niGetString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zeidon_zView_niGetString
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niGetStringFromAttributeByContext
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zeidon_zView_niGetStringFromAttributeByContext
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     zeidon_zView
 * Method:    niSetAttribute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetAttribute__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     zeidon_zView
 * Method:    niSetAttribute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetAttribute__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niInitWebSessionObject
 * Signature: (Ljava/lang/String;Lzeidon/zView;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niInitWebSessionObject
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niInitWebPage
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niInitWebPage
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niGetFocusCtrl
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zeidon_zView_niGetFocusCtrl
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niGetBannerName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zeidon_zView_niGetBannerName
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niFindOpenFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zeidon_zView_niFindOpenFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niFindErrorFields
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zeidon_zView_niFindErrorFields
  (JNIEnv *, jobject, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niCheckError
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zeidon_zView_niCheckError
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niGetDateDefaultContextFormat
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zeidon_zView_niGetDateDefaultContextFormat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niAddWebControlSubobject
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niAddWebControlSubobject
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     zeidon_zView
 * Method:    niSetAttributeFromVariable
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;CILjava/lang/String;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niSetAttributeFromVariable
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jchar, jint, jstring, jint);

/*
 * Class:     zeidon_zView
 * Method:    niMakeWebFileName
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zeidon_zView_niMakeWebFileName
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     zeidon_zView
 * Method:    niPrintReportToHTML
 * Signature: (Ljava/lang/String;Lzeidon/zView;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zeidon_zView_niPrintReportToHTML
  (JNIEnv *, jobject, jstring, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     zeidon_zView
 * Method:    niCallDialogOperation
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)S
 */
JNIEXPORT jshort JNICALL Java_zeidon_zView_niCallDialogOperation
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
