GetStringFromAttribute( (LPSTR)(LPCSTR)strObjectName,
GetStringFromAttribute( (zPCHAR) sValueStack + g_nStackPtr.lpVal,
GetStringFromAttribute( (zPCHAR)sValueStack + nStartStackPtr.lpVal,
GetStringFromAttribute( BMP.szDLLName,
GetStringFromAttribute( DirName,
GetStringFromAttribute( FileName,
GetStringFromAttribute( HeaderFileName1,
GetStringFromAttribute( HeaderFileName2,
GetStringFromAttribute( Line,
GetStringFromAttribute( POG_FileName,
GetStringFromAttribute( Sl,
GetStringFromAttribute( SourceFileName,
GetStringFromAttribute( SourceFileName1,
GetStringFromAttribute( SourceFileName2,
GetStringFromAttribute( TargetFileName,
GetStringFromAttribute( UserName,
GetStringFromAttribute( XOG_FileName,
GetStringFromAttribute( cActionType,
GetStringFromAttribute( cAutoVersion,
GetStringFromAttribute( cCancel,
GetStringFromAttribute( cDelete,
GetStringFromAttribute( cDialogStyle,
GetStringFromAttribute( cFullSize,
GetStringFromAttribute( cMetaType,
GetStringFromAttribute( cNext,
GetStringFromAttribute( cPrev,
GetStringFromAttribute( cPtrFlag,
GetStringFromAttribute( cSave,
GetStringFromAttribute( cType,
GetStringFromAttribute( cUnsignedFlag,
GetStringFromAttribute( cUsage,
GetStringFromAttribute( cWork,
GetStringFromAttribute( cZeidonType,
GetStringFromAttribute( g_lpEventAct + uLth,
GetStringFromAttribute( pchFileName + zstrlen( pchFileName ),
GetStringFromAttribute( sTag,
GetStringFromAttribute( sWorkExpr.szText,
GetStringFromAttribute( strDomainName,
