GetStringFromAttribute( (LPSTR)(LPCSTR)strObjectName,
GetStringFromAttribute( (zPCHAR) sValueStack + g_nStackPtr.lpVal,
GetStringFromAttribute( (zPCHAR)sValueStack + nStartStackPtr.lpVal,
GetStringFromAttribute( BMP.szDLLName,
GetStringFromAttribute( DirName,
GetStringFromAttribute( FileName,
GetStringFromAttribute( HeaderFileName1,
GetStringFromAttribute( HeaderFileName2,
GetStringFromAttribute( Line,
GetStringFromAttribute( POG_FileName,
GetStringFromAttribute( Sl,
GetStringFromAttribute( SourceFileName,
GetStringFromAttribute( SourceFileName1,
GetStringFromAttribute( SourceFileName2,
GetStringFromAttribute( TargetFileName,
GetStringFromAttribute( UserName,
GetStringFromAttribute( XOG_FileName,
GetStringFromAttribute( cActionType,
GetStringFromAttribute( cAutoVersion,
GetStringFromAttribute( cCancel,
GetStringFromAttribute( cDelete,
GetStringFromAttribute( cDialogStyle,
GetStringFromAttribute( cFullSize,
GetStringFromAttribute( cMetaType,
GetStringFromAttribute( cNext,
GetStringFromAttribute( cPrev,
GetStringFromAttribute( cPtrFlag,
GetStringFromAttribute( cSave,
GetStringFromAttribute( cType,
GetStringFromAttribute( cUnsignedFlag,
GetStringFromAttribute( cUsage,
GetStringFromAttribute( cWork,
GetStringFromAttribute( cZeidonType,
GetStringFromAttribute( g_lpEventAct + uLth,
GetStringFromAttribute( pchFileName + zstrlen( pchFileName ),
GetStringFromAttribute( sTag,
GetStringFromAttribute( sWorkExpr.szText,
GetStringFromAttribute( strDomainName,
GetStringFromAttribute( sz + 0,
GetStringFromAttribute( sz + 0,
GetStringFromAttribute( sz + 100,
GetStringFromAttribute( sz + 100,
GetStringFromAttribute( sz + 50,
GetStringFromAttribute( sz + 50,
GetStringFromAttribute( sz + zstrlen( sz ),
GetStringFromAttribute( sz + zstrlen( sz ),
GetStringFromAttribute( szAppViewName + 10,
GetStringFromAttribute( szAppViewName + 11,
GetStringFromAttribute( szBlob + 1,
GetStringFromAttribute( szBuffer + 19,
GetStringFromAttribute( szCFileSpec + nLth,
GetStringFromAttribute( szCPLR_CPL_Name + zstrlen( szCPLR_CPL_Name ),
GetStringFromAttribute( szCtrlBOI + nLth,
GetStringFromAttribute( szCurrentType /* Returned String */,
GetStringFromAttribute( szDomainName,
GetStringFromAttribute( szERR_Msg + zstrlen( szERR_Msg ),
GetStringFromAttribute( szEntityName + 4,
GetStringFromAttribute( szErrMsg + zstrlen( szErrMsg ),
GetStringFromAttribute( szFileName + nLth,
GetStringFromAttribute( szFileName + zstrlen( szFileName ),
GetStringFromAttribute( szFileName + zstrlen( szFileName ),
GetStringFromAttribute( szFileSpec + nLength,
GetStringFromAttribute( szFileSpec + nRC,
GetStringFromAttribute( szMetaFileName + nMetaLth,
GetStringFromAttribute( szMsg + 27,
GetStringFromAttribute( szMsg + 27,
GetStringFromAttribute( szMsg + 50,
GetStringFromAttribute( szMsg + 50,
GetStringFromAttribute( szMsg + 80,
GetStringFromAttribute( szMsg + 80,
GetStringFromAttribute( szMsg + zstrlen( szMsg ),
GetStringFromAttribute( szMsg + zstrlen( szMsg ),
GetStringFromAttribute( szMsg + zstrlen( szMsg ),
GetStringFromAttribute( szMsg + zstrlen(szMsg),
GetStringFromAttribute( szMsg + zstrlen(szMsg),
GetStringFromAttribute( szName + 1,
GetStringFromAttribute( szOpName + nLth,
GetStringFromAttribute( szOpName + nLth,
GetStringFromAttribute( szOperationName,
GetStringFromAttribute( szParam + nLth,
GetStringFromAttribute( szRecName + zstrlen( szRecName ),
GetStringFromAttribute( szRecName + zstrlen( szRecName ),
GetStringFromAttribute( szRemoteWndTag + nRemoteDlgTagLth,
GetStringFromAttribute( szSourceFileName + zstrlen( szSourceFileName ),
GetStringFromAttribute( szSourceFileName + zstrlen( szSourceFileName ),
GetStringFromAttribute( szTag + nOffset,
GetStringFromAttribute( szTargetFile + nTargetDirLth,
GetStringFromAttribute( szTemp + zstrlen( szTemp ),
GetStringFromAttribute( szTemp + zstrlen( szTemp ),
GetStringFromAttribute( szTempName + lLth,
GetStringFromAttribute( szTempName1 + 1,
GetStringFromAttribute( szTempString + 1,
GetStringFromAttribute( szTempString + 100,
GetStringFromAttribute( szTempString + 8,
GetStringFromAttribute( szTempString + k,
GetStringFromAttribute( szTempString + nLth + nLth2,
GetStringFromAttribute( szTempString + nLth,
GetStringFromAttribute( szTempString + nLth1 + nLth2,
GetStringFromAttribute( szTempString + nLth1,
GetStringFromAttribute( szTempString + ulLth,
GetStringFromAttribute( szText + nLth,
GetStringFromAttribute( szVEA + nLth,
GetStringFromAttribute( szVarName + nVarIndex,
GetStringFromAttribute( szWork + zstrlen( szWork),
GetStringFromAttribute( szWork + zstrlen( szWork),
GetStringFromAttribute( szWorkMessage + 3,
GetStringFromAttribute( szWorkMessage + 3,
GetStringFromAttribute( szWorkMessage + 64,
GetStringFromAttribute( szWorkMessage + 64,
GetStringFromAttribute( szXPGFileName + nLth,
